---
- name: Uncordon Node
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf uncordon {{ inventory_hostname  }}
  when: agorakube_base_components.kubernetes.drain | bool == True
  retries: 300
  delay: 10
  run_once: true
  delegate_to: "{{ item }}"
  with_items:
  - "{{ groups['deploy'] }}"
  ignore_errors: yes
  register: drain_status
  until: drain_status is not failed
